# Generated by Django 4.1.3 on 2022-11-12 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper_name', models.CharField(max_length=30)),
                ('wallpaper_date', models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 12, 12, 51, 54, 40627))),
            ],
        ),
    ]
