# Generated by Django 4.1.3 on 2022-11-12 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpapers',
            name='wallpaper_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 12, 13, 6, 24, 149705)),
        ),
    ]
