# Generated by Django 4.1.3 on 2022-11-12 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_wallpapers_wallpaper_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper_name', models.CharField(max_length=30)),
                ('wallpaper_date', models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 12, 14, 8, 15, 706465))),
            ],
        ),
        migrations.DeleteModel(
            name='Wallpapers',
        ),
    ]
