# Generated by Django 4.1.3 on 2022-11-12 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wallpaper_delete_wallpapers'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='wallpaper_image',
            field=models.ImageField(default='wallpaper', upload_to='main/wallpapers'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='wallpaper_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 12, 14, 11, 6, 307780)),
        ),
    ]
