# Generated by Django 4.1.3 on 2022-11-12 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_wallpaper_wallpaper_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='wallpaper_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 12, 14, 42, 2, 204493)),
        ),
    ]
