# Generated by Django 4.1.3 on 2022-11-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_wallpaper_wallpaper_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallpaper',
        ),
    ]
