# Generated by Django 4.1.3 on 2022-11-15 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper_name', models.CharField(max_length=30)),
                ('wallpaper_image', models.ImageField(default='wallpaper', upload_to='main/wallpapers')),
                ('wallpaper_date', models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 15, 12, 48, 3, 923743))),
            ],
        ),
    ]
