# Generated by Django 4.1.3 on 2022-11-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='wallpaper_date',
            field=models.DateTimeField(verbose_name='Date Published'),
        ),
    ]
