# Generated by Django 4.1.3 on 2022-11-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancing', '0002_alter_wallpaper_wallpaper_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='wallpaper_drive_url',
            field=models.URLField(default=''),
        ),
    ]
