# Generated by Django 4.1.3 on 2022-11-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_link',
            field=models.URLField(default='Resume link'),
        ),
    ]
