# Generated by Django 4.1.3 on 2022-11-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_resume_resume_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_link',
            field=models.URLField(default=''),
        ),
    ]
